{% set name = "sudachipy" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SudachiPy-{{ version }}.tar.gz
  sha256: 3d1c9086ff09afacc34d02fdb2112aab7cff1d78f0d4b81f78b9ba01c36d4888

build:
  entry_points:
    - sudachipy=sudachipy.command_line:main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - wheel
    - setuptools-rust
    - pip
  run:
    - python

test:
  imports:
    - sudachipy
  commands:
    - pip check
    - sudachipy --help
  requires:
    - pip

about:
  home: https://github.com/WorksApplications/sudachi.rs/tree/develop/python
  summary: Python version of Sudachi, the Japanese Morphological Analyzer
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apmorton
